### ISSUE TITLE
how to communicate with a REST API?

### ISSUE THREAD

**Issue by ghost** [javipalanca/spade#14]
To communicate with a SPADE agent from a REST API
where and how to send information to the agent?

In the opposite stream, from the agent to the API it is not in question. I mean to send a message from the REST API that the agent receives.
What is the address to which I must send messages?
(would be interesting to understand how to use the WUI from SPADE)

Regards.

**Comment by javipalanca** [comment]
The approach with SPADE 3.0+ is to have a small core and a lot of plugins.
See https://spade-mas.readthedocs.io/en/latest/extending.html
