### ISSUE TITLE
Block receive not behaving as expected

### ISSUE THREAD

**Issue by cgavriluta** [javipalanca/spade#21]
I am going through the tutorials and got to the "Agent Communication: Sending and Receiving Messages" step. 
In the ReceiveBehav class the line `self.msg = self._receive(True, 10)` is expected to block the behavior for 10 seconds and then resume. However, when I run it, nothing happens. I would expect, that given no message, the agent would print "I waited but got no message" every 10 seconds. 
I checked and the behaviour enters the `_process` method only once. It is like there is no difference between `self._receive(True, 10)` and `self._receive(True)`.

Any idea on what the problem might be? Thanks.

**Comment by fiery-heron** [comment]
Hi.
The reciever example does not work. The line:

ab = self.AnotherBehav()

is missing before the last line of the _setup method (before adding
the template).

**Comment by febefeebs** [comment]
Did you fix the problem?? I think I have the same, I'm running a receiving agent without sending anything and it prints in less than 10 seconds that is has received a message, and I don't know what is happening.
This is what is taking as a message...
![cod](https://user-images.githubusercontent.com/38019508/38568869-5f474d0e-3caf-11e8-8c41-ae5568975487.PNG)

Do you have any idea of what could be happening?? 
Thanks!

**Comment by mschatten** [comment]
On Tue, Apr 10, 2018 at 6:09 PM febefeebs <notifications@github.com> wrote:

> Did you fix the problem?? I think I have the same, I'm running a
receiving agent without sending anything and it prints in less than 10
seconds that is has received a message, and I don't know what is happening.
> This is what is taking as a message...

> Do you have any idea of what could be happening??
> Thanks!


I believe what you get is a presence notification from the AMS agent. You
can avoid that by using a template that does not correspond to that message.

Best,

M.
--
Markus Schatten, PhD
Associate professor and head of Artificial Intelligence Lab
University of Zagreb
Faculty of Organization and Informatics
Pavlinska 2, 42000 Varazdin, Croatia
http://www.foi.hr/nastavnici/schatten.markus/index.html
http://www.researchgate.net/profile/Markus_Schatten1
http://ai.foi.hr
