### ISSUE TITLE
Interperability with other FIPA platform (JADE) ?

### ISSUE THREAD

**Issue by remipannequin** [javipalanca/spade#24]
Hi, 

I would like to know if SPADE is interoperable with other FIPA agent platforms, for instance JADE ?

If someone already did it, it would be great to have an example... And if someone think its not possible, it would be great to know before investing time in it. Otherwise, I'm planning to give it a try.

Rémi

**Comment by javipalanca** [comment]
Hi @remipannequin.
There's an http message transport plugin to communicate with other platforms that support FIPA HTTP. This was tested with JADE some time ago. It *should* still work.
You have an example of how to use http in spade in the file https://github.com/javipalanca/spade/blob/master/test/httpTestCase.py

Hope this helps.
