### ISSUE TITLE
The ports not getting free after running a program once

### ISSUE THREAD

**Issue by kiranvasudev** [javipalanca/spade#28]
Hello,
 I am suddenly facing this issue where I can run code using SPADE just once. When I run the same code for the second time, I get the error "Could not open port xxxx". When I restart my computer, and rerun the same code, it works perfect, only once though. Is there something I am doing wrong? I am running the runTest.py code from the auction folder in the examples. 
I have tried re running the code in an Anaconda environment as well as the normal python environment. Please find attached a screenshot of the error I am getting. 
![screenshot](https://user-images.githubusercontent.com/16002904/27985531-a96be1d4-63ec-11e7-94e2-b884e87a815a.png)

Would be really helpful if you could help fix this issue.

Thank you

**Comment by javipalanca** [comment]
Next release of SPADE (3.0) will fix this issue. Stay tuned! :)
