### ISSUE TITLE
Log in SPADE Platform

### ISSUE THREAD

**Issue by miguel1995** [javipalanca/spade#30]

**Comment by miguel1995** [comment]
Hello I'm new in SPADE. 
I have successfully installed SPADE.

![image](https://user-images.githubusercontent.com/4366456/31156478-43cd99ee-a87a-11e7-9917-8b02e1853b00.png)

But when I go to Login option. It throw a password box
![image](https://user-images.githubusercontent.com/4366456/31156550-b29d70c4-a87a-11e7-92ae-2a4ede2a350e.png)

could you tell me how I log in the platform? What is the password?
I do not remember having entered a password

Thank you.

**Comment by jonas912** [comment]
Hello @miguel1995,

could you please tell me how you got to the web interface? I'm new to SPADE and was looking through the documentation but didn't find anything about an UI.

Thank you

**Comment by miguel1995** [comment]
Hello @jonas912. Yes, this there are not in the documentation  :(.

I assume that you have already downloaded and installed the packages.
And then, you have to go to the console:

**1.** write:  _configure.py localhost_   .  You have to write the IP address of your server. In my case, I wanted to use my localhost Address.
 
![image](https://user-images.githubusercontent.com/4366456/31461380-f98a639c-ae8e-11e7-9d75-bb6755ffdf45.png)

**2.**  write: _runspade.py_  . This will show you a port which you can enter to the web platform.

![image](https://user-images.githubusercontent.com/4366456/31461502-4fd7859a-ae8f-11e7-8f07-db44f6b76f2b.png)

**3** Finally, you have to go to your browser and type _localhost:8008_

![image](https://user-images.githubusercontent.com/4366456/31462121-218ce66a-ae91-11e7-8704-d589f77afc6c.png)

But, I still do not know what the password is to enter :(.

If you find out. I would appreciate it if you told me.

**Comment by jonas912** [comment]
Thanks to your fast reply @miguel1995 , I finally got access to the Web UI. Moreover I could log-in by entering the standard-password **_secret_** . Hope this works for you too.
