### ISSUE TITLE
SPADE 3 DummyAgent Example: RuntimeError regarding Asyncio

### ISSUE THREAD

**Issue by L-Piao** [javipalanca/spade#41]
Dear all,

I've been playing with the SPADE 3 "develop branch" and faced an Asyncio-related issue with Jupyter Notebook.

I simply ran the quick start example in SPADE 3 documentation Ch5.1:

> import spade.agent
> 
> class DummyAgent(spade.agent.Agent):
>     def setup(self):
>         print("Hello World! I'm agent {}".format(str(self.jid)))
> 
> dummy = DummyAgent("blabla", "blabla")
> 
> dummy.start()
> dummy.stop()

By "dummy.start()" Jupyter Notebook bounces back an error as follows. However, it doesn't happen if I run the .py-file using command prompt.

> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-6-51f95b602a4e> in <module>()
> ----> 1 dummy.start()
> 
> C:\ProgramData\Anaconda3\lib\site-packages\spade-3.0.0-py3.6.egg\spade\agent.py in start(self, auto_register)
>      48             self.register()
>      49 
> ---> 50         self.aiothread.connect()
>      51         self.aiothread.start()
>      52         self._alive.set()
> 
> C:\ProgramData\Anaconda3\lib\site-packages\spade-3.0.0-py3.6.egg\spade\agent.py in connect(self)
>     239         self.conn_coro = self.client.connected()
>     240         aenter = type(self.conn_coro).__aenter__(self.conn_coro)
> --> 241         self.stream = self.loop.run_until_complete(aenter)
>     242         logger.info(f"Agent {str(self.jid)} connected and authenticated.")
>     243 
> 
> C:\ProgramData\Anaconda3\lib\asyncio\base_events.py in run_until_complete(self, future)
>     453         future.add_done_callback(_run_until_complete_cb)
>     454         try:
> --> 455             self.run_forever()
>     456         except:
>     457             if new_task and future.done() and not future.cancelled():
> 
> C:\ProgramData\Anaconda3\lib\asyncio\base_events.py in run_forever(self)
>     410         if events._get_running_loop() is not None:
>     411             raise RuntimeError(
> --> 412                 'Cannot run the event loop while another loop is running')
>     413         self._set_coroutine_wrapper(self._debug)
>     414         self._thread_id = threading.get_ident()
> 
> RuntimeError: Cannot run the event loop while another loop is running

Local setup:
OS: Windows 10 x64, 
Python 3.65
Anaconda 1.8.7
Jupyter Notebook 5.5.0

Thanks for any hints!

**Comment by javipalanca** [comment]
seems like jupiter also uses an event loop. need to check...
