### ISSUE TITLE
The done( ) in OneShotBehaviour

### ISSUE THREAD

**Issue by hdonancio** [javipalanca/spade#47]
* SPADE version: SPADE 3.0.9
* Python version: Python 3.6.7
* Operating System: Lubuntu 18.04

### Description
Hi,
I trying use the done() command to receive a return when a OneShotBehaviour( ) has finished, but I don't have success. Here an example that I did:

```
<--- Import behaviour from another module --->
from protocols.generic.Subscribe import SubscribeXMPP

<--- In another behaviour inside of the Agent class... --->
class SetupBehaviour(OneShotBehaviour):
        async def run(self):
        	setup = open("setup.txt","r")
            	lines = setup.readlines()
            	
                for line in lines:
                    self.agent.name = line
                    b1 = SubscribeXMPP()
                    self.agent.add_behaviour(b1)

                    print(b1.done()) 

                    while(b1.done() is False):
                        time.sleep(1)

                    print(b1.done())   
```

I expected that the b1.done( ) return at first False as a value, and when the behaviour are finished, his value is True. This happen, but the behaviour only execute (or print in the screen) after the alternance of this values and work only with the last line in lines.

### Example

Supposing in setup.txt this lines:

agenta
agentb
agentc

and the SubscribeXMPP(OneShotBehaviour) execute a bash command to add each one of this lines as a agent connected in Prosody and after this, create a new agent in SPADE, the result is:

```
False
True
False
True
False 
True

Hello World! I'm agent agentc@localhost
```

I suspect that I don't understand the done() command exactly how he work.

Thanks in advance!

**Comment by javipalanca** [comment]
The ``done()`` command modifies the behaviour internal state, which is probably not  a good decision. My bad.
In the meantime, you could query the ``_already_executed`` flag to know whether the behaviour has 
finished or not.

In next versions I'll change the done() method to do not change the internal flag, and only query it.

**Comment by javipalanca** [comment]
BTK, you may also use the ``kill()`` and ``is_killed()`` methods by killing your behavior at the end of its ``run``.
