### ISSUE TITLE
can't install spade

### ISSUE THREAD

**Issue by SouGit** [javipalanca/spade#48]
* SPADE version:3.0.9
* Python version:3.7
* Operating System: windows 8.1 4bits

I'm trying to install spade using pip and I got these messages:
 
failed building wheel for lxml
could not fing function xmlCheckVersion in library libxml2. Is libxml2 installed?
Rolling back uninstall of xml.

When I try to install lxml, I have this message: requirements alredy satisfied.
When I try to install libxml2 I have this message: Could not find a version that satisfies the requirement.

I need help please!

**Comment by javipalanca** [comment]
Hi. This is probably an issue that has appeared when installing SPADE with anaconda and Python 3.7.
For any reason lxml does not work with those elements.
I recommend you to downgrade to python 3.6, where the lxml error is not present.

Use:
`conda install python=3.6`

**Comment by SouGit** [comment]
Thank you for your reply.
I will downgrade to 3.6 and retry it.
Best regards.
    Le lundi 3 décembre 2018 à 12:22:29 UTC−5, Javi Palanca <notifications@github.com> a écrit :  
 
 
Hi. This is probably an issue that has appeared when installing SPADE with anaconda and Python 3.7.
For any reason lxml does not work with those elements.
I recommend you to downgrade to python 3.6, where the lxml error is not present.

Use:
conda install python=3.6

**Comment by SouGit** [comment]
Yes, it does work.
Now when I tried my first example I have this error message:
import lxml.etree as etree
AttributeError: module 'lxml' has no attribute 'etree'
The code I tried:

from spade import agent




class DummyAgent(agent.Agent):

 def setup(self):

 print("Hello World! I'm agent {}".format(str(self.jid)))




dummy = DummyAgent("your_jid@your_xmpp_server", "your_password")

dummy.start()




dummy.stop()

Do you have an idea ?
Thanks

    Le lundi 3 décembre 2018 à 12:22:29 UTC−5, Javi Palanca <notifications@github.com> a écrit :  
 
 
Hi. This is probably an issue that has appeared when installing SPADE with anaconda and Python 3.7.
For any reason lxml does not work with those elements.
I recommend you to downgrade to python 3.6, where the lxml error is not present.

Use:
conda install python=3.6

**Comment by javipalanca** [comment]
Try with:
``pip install lxml``

You could also try to reinstall spade after downgrading to python3.6: ``pip install spade``
