### ISSUE TITLE
Compare agent jid in trace.py

### ISSUE THREAD

**Issue by leaf8** [javipalanca/spade#52]
* SPADE version: 3.0.9
* Python version: 3.6.6
* Operating System: Debian 9

### Description

When i use web user interface i can`t see opponent agent message in chat box

### What I Did

My issue change private function in spade/trace.py:
1 Old code:
def _agent_in_msg(agent, msg):
    return msg.to == agent or msg.sender == agent

2 New code:
def _agent_in_msg(agent, msg):
    return str(msg.to).startswith(str(agent)) or str(msg.sender).startswith(str(agent))

All problem is a resource in JID

**Comment by javipalanca** [comment]
Can you please explain the problem a little more?
I can't understand what is going wrong.
Thanks!

**Comment by javipalanca** [comment]
I see the problem. In the next release the bug will be fixed. Thank you!
