### ISSUE TITLE
Error importing spade

### ISSUE THREAD

**Issue by DaniSalva** [javipalanca/spade#56]
* SPADE version: 3.1.0
* Python version: 3.6.8
* Operating System: Windows 10

### Description

I installed succesfully SPADE (tried from sources and pip) but when I try to import the package, it gives me one error.

### What I Did

>>> from spade import agent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "........\spade.py", line 3, in <module>
    from spade.agent import Agent
ModuleNotFoundError: No module named 'spade.agent'; 'spade' is not a package

If I type "pip list" I can see the spade package installed.

**Comment by javipalanca** [comment]
I see you've closed the issue, so I guess you've found the error. Just in case, the error was to have called your script spade.py, which causes a problem to the python import system, as it is called the same as the ``spade``module
