### ISSUE TITLE
DummyAgent freezes the script execution

### ISSUE THREAD

**Issue by ErtHub** [javipalanca/spade#58]
* SPADE version: 3.1.2
* Python version: 3.7.3
* Operating System: Windows 10 Home

### Description

Running the DummyAgent code from the Quick Start section of SPADE documentation causes the script to be unable to finish properly.

Code:

```
from spade import agent
class DummyAgent(agent.Agent):
    async def setup(self):
        print("Hello World! I'm agent{}".format(str(self.jid)))

dummy = DummyAgent("your_jid@your_xmpp_server", "your_password")

dummy.start()

dummy.stop()
```

Output:

```
Hello World! I'm agent your_jid@your_xmpp_server
<command line prompt missing>
```

**Comment by javipalanca** [comment]
Hi.
This is because the SPADE core is still running in the process, waiting for more agents.
I've implemented a quit_spade function that unfortunately isn't still in the docs.
Try:

```
from spade import agent
from spade import quit_spade

class DummyAgent(agent.Agent):
    async def setup(self):
        print("Hello World! I'm agent{}".format(str(self.jid)))

dummy = DummyAgent("your_jid@your_xmpp_server", "your_password")

dummy.start()

dummy.stop()

quit_spade()
```

**Comment by ErtHub** [comment]
Hi.
Thank you for turning your attention to my issue. I have tried running the code you suggested, however I get as a result a different type of error now:

```
C:\Users\jatko\AppData\Local\Programs\Python\Python37-32\lib\site-packages\spade\container.py:136: RuntimeWarning: coroutine 'wait_for' was never awaited
  asyncio.wait_for(future, timeout=5)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending coro=<Agent._async_start() running at C:\Users\jatko\AppData\Local\Programs\Python\Python37-32\lib\site-packages\spade\agent.py:86> cb=[_chain_future.<locals>._call_set_state() at C:\Users\jatko\AppData\Local\Programs\Python\Python37-32\lib\asyncio\futures.py:355]>
Task was destroyed but it is pending!
task: <Task pending coro=<Agent._async_stop() running at C:\Users\jatko\AppData\Local\Programs\Python\Python37-32\lib\site-packages\spade\agent.py:254> cb=[_chain_future.<locals>._call_set_state() at C:\Users\jatko\AppData\Local\Programs\Python\Python37-32\lib\asyncio\futures.py:355]>
sys:1: RuntimeWarning: coroutine 'Agent._async_start' was never awaited
sys:1: RuntimeWarning: coroutine 'Agent._async_stop' was never awaited
```

It appears to me that ```dummy.start()``` and ```dummy.stop()``` calls should be preceded with an ```await``` command, however I can't seem to figure out how to do it properly. Is there anything else I'm not doing right?

**Comment by javipalanca** [comment]
Take a look at the documentation about that: https://spade-mas.readthedocs.io/en/latest/usage.html#creating-an-agent-from-within-another-agent

`start` and `stop` are used differently from inside a coroutine and from outside.
Basically, if you call `start` or `stop` in a coroutine you must await it. Otherwise not.

**Comment by javipalanca** [comment]
By the way, at SPADE 3.1.2 the bug of quit_spade was fixed. So, please ensure you are upgraded :)
