### ISSUE TITLE
How to measure agent's performance? 

### ISSUE THREAD

**Issue by fszymaniak** [javipalanca/spade#61]
* SPADE version: 3.1.3
* Python version: 3.7
* Operating System: Win10
* XMPP server: ejabber version: 19.05

### Description

I would like to ask about receiving performance measurements in spade during exchanging messages. For example, latency, bandwidth etc. Is there any chance to measure them?

Thank you for such a good job during developing and maintaining this framework!

**Comment by javipalanca** [comment]
Hi.
There is nothing made to measure performance in SPAD (yet). You need to implement your own tests in such case.
