### ISSUE TITLE
How to add custom method calls to event loop?

### ISSUE THREAD

**Issue by ccarstens** [javipalanca/spade#62]
* SPADE version: 3.1.3
* Python version: 3.7.4
* Operating System: macOS 10.14.6

### Description

I want to use a speech synthesis package called pyttsx3 which offers its own event loop for the execution of the synthesis.
When using their event loop the voice output blocks everything else until I stop their event loop, which comes with a 1200ms delay.

Pyttsx3 als offers to use a custom event loop as described [here](https://pyttsx3.readthedocs.io/en/latest/engine.html#using-an-external-event-loop).

Where would I call `engine.iterate()`?

Can I add Tasks or method calls to Spade's event loop?

Thank you for helping me! <3

**Comment by javipalanca** [comment]
`agent.loop` is the event loop of all the agents in the same process. You can access it also through the agent container:
```
container = Container()  # anywhere, since it is a singleton
container.loop
```

**Comment by ccarstens** [comment]
Thank you, Javi!
Since the modules I'm using aren't implementing asyncio I ended up putting all the IO in it's own process while using the agent's run() method to monitor a queue with user responses.
