### ISSUE TITLE
Finishing program after OneShotBehaviour

### ISSUE THREAD

**Issue by sikorski-as** [javipalanca/spade#85]
* SPADE version: 3.1.4
* Python version: 3.7.1
* Operating System: Win10

I'm using Pycharm Community 2018.3, if it matters.
### Description

I tried to make an agent with a simple one-shot-behaviour that sends a message and waits a while for a reply. Then agent logs if an answer arrived or not and then finishes the program.

Basically, something like that (irrelevant parts omitted/replaced with ...):
```
class TestAgent(Agent):
    def __init__(self, *args, **kwargs):
        super(TestAgent, self).__init__(*args, **kwargs)

    async def setup(self):
        self.add_behaviour(TestAgent.TestMessage())

    class TestMessage(OneShotBehaviour):
        async def run(self):
            await self.send(...)
            reply = await self.receive(timeout=5)
            # do something here

tester = TestAgent('tester@localhost', 'tester')
tester.start()
```
But the code above keeps running eventhough the TestMessage behaviour finishes. 

### What I Did
I tried `await self.agent.stop()` at the end of `run` function of `TestMessage` behaviour (`#do something here`) but it still keeps running. I also tried `quit_spade()` there which basically worked and stopped the execution but printed:
```
...\venv\lib\site-packages\spade\container.py:117: RuntimeWarning: coroutine 'Agent._async_stop' was never awaited
  agent.stop()
```
Is it fine to use quit_spade() in such context (even if it gives RuntimeWarning)? Or did I mess something? I just want a simple agent that send one message and terminates.

**Comment by javipalanca** [comment]
`start` is not a blocking method. So if you don't make anything after the start call the script finishes automatically.
It is a common use case to make an active wait (e.g. `while agent.is_alive()`) to wait until the agent is finished. Go to the examples folder to see some examples.

Also, when you call `quit_spade` you stop every agent in the process and finishes it.

**Comment by sikorski-as** [comment]
Active wait doesn't seem to be the coolest solution but it's fine for my case. Thanks for the answer!
