### ISSUE TITLE
[API] how to create REST API and connect Redis

### ISSUE THREAD

**Issue by giacat-tran0198** [javipalanca/spade#94]
* SPADE version: lastest
* Python version: lastest
* Operating System: win 10

### Description
Hello.
I'm trying to create a web app that apply my educational , an i want to implement a spade environment in order to execute some complex process using a few agents and connect with Redis. I want to send myAgent from a request GET(POST, UPDATE or DELETE) from API, after it is resolved,, the agent will return the result. For example: post the link /api/sum with list by json like:

```
{
  "value": [ 1, 2, 3]
}
```
And myAgent will calcule, and return a result json like:

```
{
  "result": 6
}
```
Is there any solves or recommendations to this? How to create this API and how to connect system with Redis?

**Comment by javipalanca** [comment]
https://spade-mas.readthedocs.io/en/latest/web.html#json-responses

**Comment by giacat-tran0198** [comment]
@javipalanca I've read it, but I don't know how to send back result from agent after done? Could you give me an example?
